In [1]:
import pandas as pd
import numpy as np

In [12]:
# Question 1
pd.__version__

'2.0.3'

In [3]:
df = pd.read_csv('housing.csv')

In [13]:
# Question 2

In [4]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [14]:
# Question 3

In [5]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [15]:
# Question 4

In [6]:
df['ocean_proximity'].nunique()

5

In [16]:
# Question 5

In [10]:
near_bay = df[df['ocean_proximity'] == 'NEAR BAY']
near_bay

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
19067    -122.45     38.28                20.0       3306.0           503.0   
19068    -122.47     38.29                14.0       3732.0           846.0   
19069    -122.45     38.27                25.0       5024.0           881.0   
19077    -122.49     38.27                 8.0       5092.0           988.0   
19104    -122.51     38.17                 8.0       5875.0          1115.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
19067      1374.0       460.0         5.7984            297600.0   
19068      1277.0       775.0         2.5658            208000.0   
19069      1994.0       838.0         4.2237            262300.0   
19077      1657.0       936.0         3.5625            213200.0   
19104      2808.0      1029.0         3.6392            246300.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
19067        NEAR BAY  
19068        NEAR BAY  
19069        NEAR BAY  
19077        NEAR BAY  
19104        NEAR BAY  

[2290 rows x 10 columns]

In [11]:
near_bay['median_house_value'].mean()

259212.31179039303

In [17]:
# Question 6
mean_original = df['total_bedrooms'].mean()
mean_original

537.8705525375618

In [20]:
df['total_bedrooms'].fillna(mean_original, inplace = True)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [24]:
# no missing value anymore

In [25]:
mean_after = df['total_bedrooms'].mean()
mean_after

537.8705525375617

In [46]:
# 7.2

In [51]:
options_df = df[['housing_median_age','total_rooms','total_bedrooms']]
options_df = options_df.head()

In [47]:
# 7.3

In [52]:
X = options_df.values
X

array([[  41.,  880.,  129.],
       [  21., 7099., 1106.],
       [  52., 1467.,  190.],
       [  52., 1274.,  235.],
       [  52., 1627.,  280.]])

In [53]:
# 7.4

In [54]:
XT = X.transpose()
XT

array([[  41.,   21.,   52.,   52.,   52.],
       [ 880., 7099., 1467., 1274., 1627.],
       [ 129., 1106.,  190.,  235.,  280.]])

In [39]:
XTX = XT.dot(X)
XTX

array([[2.01984850e+07, 1.35332892e+09, 2.83204712e+08],
       [1.35332892e+09, 2.41621366e+11, 4.67660348e+10],
       [2.83204712e+08, 4.67660348e+10, 9.59926544e+09]])

In [55]:
# 7.5

In [56]:
XTX_invs = np.linalg.inv(XTX)
XTX_invs

array([[ 8.47988169e-08,  1.62386103e-10, -3.29291640e-09],
       [ 1.62386103e-10,  7.28537219e-11, -3.59722129e-10],
       [-3.29291640e-09, -3.59722129e-10,  1.95383149e-09]])

In [57]:
# 7.6

In [58]:
y = np.array([950,1300,800,1000,1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [59]:
# Result
result1 = XTX_invs.dot(XT)
result1

array([[ 3.19486505e-06, -7.08411443e-07,  4.02210478e-06,
         3.84258302e-06,  3.75172408e-06],
       [ 2.43649508e-08,  1.22746005e-07,  4.69732828e-08,
         1.67250187e-08,  2.62548867e-08],
       [-1.99520785e-07, -4.61881017e-07, -3.27716034e-07,
        -1.70367247e-07, -2.09426741e-07]])

In [60]:
result2 = result1.dot(y)
result2

array([ 0.0140517 ,  0.00027115, -0.00149478])

In [61]:
w = result2
w

array([ 0.0140517 ,  0.00027115, -0.00149478])